on: [push] # push 代码时触发
jobs: 
    deploy: 
        runs-on: ubuntu-latest
        name: Tencent Cloudbase Github Action Example
        steps: 
        - name: Checkout
          uses: actions/checkout@v2
        # 使用云开发 Github Action 部署
        - name: Deploy static to Tencent CloudBase
          id: deployStatic
          uses: TencentCloudBase/cloudbase-action@v1.1.1
          with: 
            # 云开发的访问密钥 secretId 和 secretKey
            secretId: ${{ AKIDc2FExOZT6SWKBpCJAk36tVsyoNffPr2w }}
            secretKey: ${{ e17wJRIr9BvOaVAXdS0HH0UhcGdjY6NO }}
            # 云开发的环境id
            envId: ${{ blog-5g63hwjed11d36ae }}
            # Github 项目静态文件的路径
            staticSrcPath: public
